name: Fastlane Action
description: An action for executing fastlane lanes
author: "maierj"
branding:
  icon: "archive"
  color: "gray-dark"
inputs:
  lane:
    description: "The lane that should be executed."
    required: true
  subdirectory:
    description: "The relative path from the project root directory to the subdirectory where the fastlane folder is located."
    required: false
  bundle-install-path:
    description: "The directory where Ruby gems should be installed to and cached. If a relative path is specified, it's applied relative to the location of the Gemfile, which is either the project root or the directory from the `subdirectory` parameter."
    required: false
  skip-tracking:
    description: "The action tracks usage in Firebase by default. You can disable tracking by setting this parameter to 'true'."
    required: false
runs:
  using: node12
  main: main.js
